# SwiftLint Configuration

# Paths to include during linting
included:
  - MyApp/MyApp

# Paths to ignore during linting
excluded:
  - Pods
  - .build
  - DerivedData
  - MyApp/MyApp.xcodeproj

# Rules to disable
disabled_rules:
  - trailing_whitespace # Can be handled by editor
  - todo # TODOs are okay during development

# Rules to opt into
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - URL

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

# Rules that can be auto-corrected
# Run: swiftlint autocorrect
autocorrect_rules:
  - empty_count
  - empty_string
  - explicit_init
  - joined_default_parameter
  - redundant_nil_coalescing

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    message: "Use Logger instead of print()"
    severity: warning
    
  no_force_try:
    name: "No Force Try"
    regex: "try!"
    message: "Avoid force try. Handle errors properly."
    severity: error

# Reporter type
reporter: "xcode"
